export const BYTES_PER_MEGABYTE = 1024 * 1024
export const BYTES_PER_GIGABYTE = 1024 * 1024 * 1024

export const CLOUDFLARE_R2_FREE_STANDARD_STORAGE_BYTES_MONTH = 10 * BYTES_PER_GIGABYTE
export const CLOUDFLARE_R2_FREE_CLASS_A_OPERATIONS_MONTH = 1_000_000
export const CLOUDFLARE_R2_FREE_CLASS_B_OPERATIONS_MONTH = 10_000_000
export const CLOUDFLARE_D1_FREE_STORAGE_BYTES = 5 * BYTES_PER_GIGABYTE
export const CLOUDFLARE_D1_FREE_ROWS_READ_DAY = 5_000_000
export const CLOUDFLARE_D1_FREE_ROWS_WRITTEN_DAY = 100_000
export const PADDLEOCR_DAILY_PDF_PAGE_LIMIT = 2_000

export const DEFAULT_UPLOAD_QUOTA_BYTES = CLOUDFLARE_R2_FREE_STANDARD_STORAGE_BYTES_MONTH
export const DEFAULT_UPLOAD_QUOTA_MB = DEFAULT_UPLOAD_QUOTA_BYTES / BYTES_PER_MEGABYTE
export const DEFAULT_OCR_JOB_QUOTA = 25
export const DEFAULT_OCR_PAGE_QUOTA = PADDLEOCR_DAILY_PDF_PAGE_LIMIT
export const MAX_UPLOAD_QUOTA_BYTES = CLOUDFLARE_R2_FREE_STANDARD_STORAGE_BYTES_MONTH
export const MAX_OCR_PAGE_QUOTA = PADDLEOCR_DAILY_PDF_PAGE_LIMIT

export type QuotaLimitKey = "uploadBytesLimit" | "ocrPagesLimit"

export function clampQuotaLimit(key: QuotaLimitKey, value: number): number {
  if (key === "uploadBytesLimit") return Math.min(value, MAX_UPLOAD_QUOTA_BYTES)
  return Math.min(value, MAX_OCR_PAGE_QUOTA)
}
